- .gitignore
- benchmarking/benchmark.py
Changing plotting legend font size, argument errors for used functions and code bugs, storing all plotted images in a new directory
> Benchmark minor corrections

- base.py
- benchmarking/benchmark.py
- featurizers/fingerprints.py
- featurizers/map4_mhfp_helper_functions.py
- tests/fingerprints_tests.py
- utils/logger.py
Fix to map4 and mhfp fingerprints, implementation uniformity with other classes and their code style, implementation of sparse variant, tests for sparse and count variants. There's still no implementation or uniformity for e3fp as well as work on actual benchmark as current implementation of e3fp has bugs.
> Fix map4 and mhfp

- .pre-commit-config.yaml
- skfp/fingerprints/ecfp.py
- tests/fingerprints_tests.py
To initialize FCFP fingerprint, the user needs to pass `use_fcfp` boolean argument as True
> Add FCFP fingerprint in ECFP

- skfp/__init__.py
- skfp/fingerprints/mhfp.py
- tests/fingerprints_tests.py
Faster MHFP implementation. The previous implementation is left as MHFPlegacy. It appears that the comments and documentation for EncodeMolsBulk function are incorrect as it states that `kekulize` parameter is initialized as false as in reality it's true.
> MHFP rdkit implementation

- benchmarking/benchmark.py
- skfp/__init__.py
- skfp/fingerprints/base.py
- skfp/other/util_transformers.py
- tests/fingerprints_tests.py
Added MolFromSmiles and MolToSmiles transformers
> mol to smiles and mol from smiles

- Makefile
I was a little surprised when dependencies started to install/remove just with make
> add help to makefile

- skfp/fingerprints/layered.py
- skfp/fingerprints/pattern.py
- skfp/fingerprints/rdk.py
- tests/conftest.py
- tests/fingerprints/lingo.py
Also include small improvements to tests, which came in handy when testing this.
> RDKit and Layered fingerprints docs

- .github/workflows/python-test.yml
- .pre-commit-config.yaml
- Makefile
- README.md
- docs/modules/classes.rst
- docs/modules/metrics.rst
- docs/modules/model_selection.rst
- docs/modules/utils.rst
- poetry.lock
- pyproject.toml
- skfp/datasets/moleculenet.py
- skfp/datasets/utils.py
- skfp/fingerprints/e3fp_fp.py
- skfp/fingerprints/map.py
- skfp/metrics/__init__.py
- skfp/metrics/multioutput.py
- skfp/model_selection/__init__.py
- skfp/model_selection/grid_search.py
- skfp/model_selection/randomized_search.py
- tests/datasets/moleculenet.py
- tests/metrics/multioutput.py
- tests/model_selection/grid_search.py
- tests/model_selection/randomized_selection.py
Implementation is safe against missing values and constant columns.
> Add multioutput metrics

- docs/modules/bases.rst
- docs/modules/preprocessing.rst
- skfp/bases/__init__.py
- skfp/bases/base_filter.py
- skfp/bases/base_preprocessor.py
- skfp/preprocessing/__init__.py
- skfp/preprocessing/filters/__init__.py
- skfp/preprocessing/filters/lipinski.py
- tests/bases/base_filter.py
- tests/model_selection/splitters/scaffold_split.py
- tests/preprocessing/filters/lipinski.py
Added Lipinski Rule of 5 filter. With `BaseFilter` class, it can serve as a base for issue https://github.com/scikit-fingerprints/scikit-fingerprints/issues/197.
> Lipinski filter

- docs/modules/fingerprints.rst
- skfp/fingerprints/__init__.py
- skfp/fingerprints/vsa.py
- tests/fingerprints/vsa.py
Added VSA descriptors, almost the last one of https://github.com/scikit-fingerprints/scikit-fingerprints/issues/66 from RDKit
> Add VSA descriptors

- docs/modules/preprocessing.rst
- skfp/preprocessing/__init__.py
- skfp/preprocessing/filters/__init__.py
- skfp/preprocessing/filters/brenk.py
- tests/preprocessing/filters/brenk.py
- tests/preprocessing/filters/pains.py
- tests/sklearn_compatibility/basic_checks.py
Brenk filter, part of https://github.com/scikit-fingerprints/scikit-fingerprints/issues/197.
> Add Brenk filter

- .flake8
- skfp/bases/base_fp_transformer.py
- skfp/fingerprints/e3fp_fp.py
- skfp/fingerprints/vsa.py
- skfp/model_selection/splitters/randomized_scaffold_split.py
- skfp/model_selection/splitters/scaffold_split.py
- skfp/model_selection/splitters/utils.py
- skfp/preprocessing/filters/brenk.py
- tests/fingerprints/ghose_crippen.py
- tests/fingerprints/mordred_fp.py
- tests/preprocessing/filters/lipinski.py
- tests/sklearn_compatibility/basic_checks.py
Remove unused imports, fix some types. Also turned on unused imports error in Flake8.
> Remove unused imports and fix some types

- skfp/preprocessing/filters/surechembl.py
Add more background on SureChEMBL filter, based on uncovered information.
> Add more SureChEMBL docs

- skfp/fingerprints/pharmacophore.py
- tests/fingerprints/atom_pair.py
- tests/fingerprints/avalon.py
- tests/fingerprints/e3fp_fp.py
- tests/fingerprints/ecfp.py
- tests/fingerprints/erg.py
- tests/fingerprints/estate.py
- tests/fingerprints/getaway.py
- tests/fingerprints/ghose_crippen.py
- tests/fingerprints/klekota_roth.py
- tests/fingerprints/laggner.py
- tests/fingerprints/layered.py
- tests/fingerprints/map.py
- tests/fingerprints/mhfp.py
- tests/fingerprints/mordred_fp.py
- tests/fingerprints/morse.py
- tests/fingerprints/mqns.py
- tests/fingerprints/pattern.py
- tests/fingerprints/pharmacophore.py
- tests/fingerprints/physiochemical_properties.py
- tests/fingerprints/pubchem.py
- tests/fingerprints/rdf.py
- tests/fingerprints/rdkit_fp.py
- tests/fingerprints/secfp.py
- tests/fingerprints/topological_torsion.py
- tests/fingerprints/whim.py
Implements both improvements to pharmacophore fingerprint from https://github.com/scikit-fingerprints/scikit-fingerprints/issues/260.
> Pharmacophore enhancements

- docs/modules/fingerprints.rst
- skfp/fingerprints/__init__.py
- skfp/fingerprints/electroshape.py
- skfp/fingerprints/usr.py
- skfp/fingerprints/usrcat.py
- tests/fingerprints/electroshape.py
ElectroShape fingerprint, part of https://github.com/scikit-fingerprints/scikit-fingerprints/issues/66.
> ElectroShape fingerprint

- docs/modules/preprocessing.rst
- skfp/preprocessing/__init__.py
- skfp/preprocessing/filters/__init__.py
- skfp/preprocessing/filters/ghose.py
- skfp/preprocessing/filters/hao.py
- skfp/preprocessing/filters/pfizer.py
- skfp/preprocessing/filters/tice_herbicides.py
- skfp/preprocessing/filters/tice_insecticides.py
- tests/preprocessing/filters/ghose.py
- tests/preprocessing/filters/hao.py
- tests/preprocessing/filters/pfizer.py
- tests/preprocessing/filters/tice_herbicides.py
- tests/preprocessing/filters/tice_insecticides.py
Ghose
Pfizer
Hao
Tice Insecticides
Tice Pesticides
> Added new rules

- skfp/fingerprints/ecfp.py
> Add mention of Morgan to ECFP docs

- docs/modules/preprocessing.rst
- skfp/preprocessing/__init__.py
- skfp/preprocessing/filters/__init__.py
- skfp/preprocessing/filters/rule_of_veber.py
- tests/preprocessing/filters/rule_of_veber.py
> Added Veber filter

- poetry.lock
- pyproject.toml
* Added matplotlib dependency to evaluation poetry group
> Add matplotlib dependency to evaluation poetry group

- skfp/model_selection/splitters/maxmin_split.py
- skfp/model_selection/splitters/utils.py
- tests/model_selection/splitters/maxmin_split.py
> MaxMin split

- docs/modules/model_selection.rst
- skfp/model_selection/__init__.py
- skfp/model_selection/splitters/__init__.py
- skfp/model_selection/splitters/maxmin_split.py
Small fixes for MaxMin split, mostly docs.
> Small MaxMin split fixes

- docs/modules/preprocessing.rst
- skfp/preprocessing/__init__.py
- skfp/preprocessing/filters/__init__.py
- skfp/preprocessing/filters/rule_of_xu.py
- tests/datasets/moleculenet.py
- tests/preprocessing/filters/rule_of_xu.py
> Added Rule of Xu

- docs/modules/preprocessing.rst
- skfp/preprocessing/__init__.py
- skfp/preprocessing/filters/__init__.py
- skfp/preprocessing/filters/rule_of_reos.py
- tests/preprocessing/filters/rule_of_reos.py
Added a molecular filter based on the Rule of REOS and appropriate test cases.
> Added Rule of REOS

- skfp/model_selection/hyperparam_search/grid_search.py
- skfp/model_selection/hyperparam_search/randomized_search.py
- tests/model_selection/splitters/randomized_scaffold_split.py
- tests/model_selection/splitters/scaffold_split.py
Fix best score in hyperparameter search according to greater_is_better value.
> Fix best score in hyperparameter search

- skfp/model_selection/splitters/utils.py
Fixed splitters index fetching for Pandas types.
> Fix splitters

- skfp/preprocessing/conformer_generator.py
- skfp/preprocessing/standardization.py
1. Speed up MolStandardizer
2. Use more BasePreprocessor features in ConformerGenerator
3. Add missing docs
> MolStandardizer and ConformerGenerator enhancements

- skfp/preprocessing/input_output/smiles.py
- tests/preprocessing/input_output/smiles.py
Small fix to `.transform_x_y()`.
> MolFromSmiles fix

- docs/modules/metrics.rst
- skfp/metrics/__init__.py
- skfp/metrics/multioutput.py
- skfp/metrics/utils.py
- tests/metrics/multioutput.py
- tests/metrics/utils.py
Change `extract_multioutput_pos_proba` to `extract_pos_proba`, covering single-output case from https://github.com/scikit-fingerprints/scikit-fingerprints/issues/321
> Extract pos proba

- README.md
Paper is now published in SoftwareX, ArXiv link is secondary.
> Add SoftwareX paper citation

- README.md
Fixes import in README: https://github.com/scikit-fingerprints/scikit-fingerprints/pull/325.
> README import fix

- docs/modules/metrics.rst
- skfp/metrics/__init__.py
- skfp/metrics/auroc.py
- skfp/metrics/multioutput.py
- skfp/metrics/spearman.py
- skfp/metrics/virtual_screening.py
- tests/metrics/virtual_screening.py
Implemented RF, RIE and BEDROC metrics for virtual screening.
> Virtual screening metrics

- skfp/utils/functions.py
- tests/model_selection/splitters/utils.py
> Fix data retrieval

- CONTRIBUTING.md
- skfp/datasets/moleculenet/bace.py
- skfp/datasets/moleculenet/bbbp.py
- skfp/datasets/moleculenet/clintox.py
- skfp/datasets/moleculenet/esol.py
- skfp/datasets/moleculenet/freesolv.py
- skfp/datasets/moleculenet/hiv.py
- skfp/datasets/moleculenet/lipophilicity.py
- skfp/datasets/moleculenet/muv.py
- skfp/datasets/moleculenet/pcba.py
- skfp/datasets/moleculenet/sider.py
- skfp/datasets/moleculenet/tox21.py
- skfp/datasets/moleculenet/toxcast.py
> Add examples for dataset loading functions [moleculenet]

- docs/modules/utils.rst
- skfp/fingerprints/rdkit_2d_desc.py
- skfp/preprocessing/input_output/aminoseq.py
- skfp/preprocessing/input_output/inchi.py
- skfp/preprocessing/input_output/sdf.py
- skfp/preprocessing/input_output/smiles.py
- skfp/utils/__init__.py
- skfp/utils/functions.py
- skfp/utils/parallel.py
- skfp/utils/rdkit_logging.py
- skfp/utils/validators.py
- tests/docs_tests.py
Adds better utils docs, more tests, and improved molecular conversion docs overall.
> Add better molecular conversion docs

- README.md
Just a small update of icons in readme
> Updated Icons

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- skfp/fingerprints/autocorr.py
- skfp/fingerprints/electroshape.py
- skfp/fingerprints/estate.py
- skfp/fingerprints/ghose_crippen.py
- skfp/fingerprints/klekota_roth.py
- skfp/fingerprints/laggner.py
- skfp/fingerprints/maccs.py
- skfp/fingerprints/mordred_fp.py
- skfp/fingerprints/morse.py
- skfp/fingerprints/mqns.py
- skfp/fingerprints/rdf.py
- skfp/fingerprints/rdkit_2d_desc.py
- skfp/fingerprints/vsa.py
- tests/fingerprints/autocorr.py
- tests/fingerprints/erg.py
- tests/fingerprints/estate.py
- tests/fingerprints/mordred_fp.py
- tests/fingerprints/morse.py
- tests/fingerprints/mqns.py
- tests/fingerprints/rdf.py
- tests/fingerprints/vsa.py
- tests/preprocessing/input_output/aminoseq.py
Major part of https://github.com/scikit-fingerprints/scikit-fingerprints/issues/310, feature names for: Autocorrelation, MQNs, MoRSE, EState, RDF, VSA.
> Add more feature names

- examples/05_hyperparameter_tuning.ipynb
Added hyperparameter tuning tutorial.
> Hyperparameter tuning tutorial

- examples/06_dataset_splits.ipynb
- skfp/model_selection/splitters/maxmin_split.py
Added tutorial on datasets splits, and also fixed a few bugs in MaxMin split implementation.
> Dataset splits tutorial

- skfp/fingerprints/map.py
Small simplification of MAP fingerprint, the parts that were a bit hard to read.
> Small MAP fingerprint simplification

- .github/workflows/docs-publish.yml
- poetry.lock
Fixed typo in docs workflow definition that error the publishing flow.
> Fix typo with docs deployment

- CONTRIBUTING.md
- Makefile
Adds more explicit information about installing Pandoc for development setup. We use it in docs generation.
> Add more explicit Pandoc information

- README.md
Fixes broken tests badge in README
> Update tests badge in README

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/braun_blanquet.py
- skfp/distances/ct4.py
- skfp/distances/dice.py
- skfp/distances/harris_lahey.py
- skfp/distances/kulczynski.py
- skfp/distances/mcconnaughey.py
- skfp/distances/rand.py
- skfp/distances/simpson.py
- skfp/distances/tanimoto.py
- skfp/distances/utils.py
- tests/distances/braun_blanquet.py
- tests/distances/common.py
- tests/distances/ct4.py
- tests/distances/dice.py
- tests/distances/fraggle.py
- tests/distances/kulczynski.py
- tests/distances/mcconnaughey.py
- tests/distances/rand.py
- tests/distances/simpson.py
- tests/distances/tanimoto.py
- tests/distances/utils.py
Add McConnaughey similarity and distance
> Add McConnaughey similarity and CSC/COO arrays support

- skfp/distances/harris_lahey.py
- tests/distances/harris_lahey.py
- tests/distances/utils.py
Adds missing tests and fixes https://github.com/scikit-fingerprints/scikit-fingerprints/issues/402
> Fix Harris-Lahey similarity, add tests

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/rogot_goldberg.py
- tests/distances/rogot_goldberg.py
> Rogot-Goldberg distance

- Makefile
With this change, Makefile should print fewer things if everything goes ok.
> Small Makefile improvement

- docs/modules/distances.rst
- skfp/datasets/utils.py
- skfp/distances/__init__.py
- skfp/distances/rogot_goldberg.py
- skfp/distances/sokal_sneath.py
- tests/distances/sokal_sneath.py
Add last similarity from https://github.com/scikit-fingerprints/scikit-fingerprints/issues/228.
> Add Sokal-Sneath similarity

- docs/modules/distances.rst
- poetry.lock
- pyproject.toml
- skfp/distances/__init__.py
- skfp/distances/tanimoto.py
- skfp/fingerprints/atom_pair.py
- skfp/fingerprints/avalon.py
- skfp/fingerprints/e3fp_fp.py
- skfp/fingerprints/ecfp.py
- skfp/fingerprints/erg.py
- skfp/fingerprints/klekota_roth.py
- skfp/fingerprints/laggner.py
- skfp/fingerprints/layered.py
- skfp/fingerprints/lingo.py
- skfp/fingerprints/map.py
- skfp/fingerprints/mhfp.py
- skfp/fingerprints/mordred_fp.py
- skfp/fingerprints/pattern.py
- skfp/fingerprints/pharmacophore.py
- skfp/fingerprints/physiochemical_properties.py
- skfp/fingerprints/pubchem.py
- skfp/fingerprints/rdkit_fp.py
- skfp/fingerprints/secfp.py
- skfp/fingerprints/topological_torsion.py
- tests/distances/common.py
- tests/distances/tanimoto.py
- tests/distances/utils.py
> Add Bulk Tanimoto distance and similarity

- skfp/distances/tanimoto.py
> Small fix for bulk Tanimoto

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/rand.py
- skfp/distances/tanimoto.py
- tests/distances/rand.py
> Add Bulk Rand similarity

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/simpson.py
- tests/distances/simpson.py
> Add Bulk Simpson sim and dist

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/braun_blanquet.py
- skfp/distances/simpson.py
- tests/distances/braun_blanquet.py
> Add bulk Braun-Blanquet sim and dist

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/ct4.py
- tests/distances/ct4.py
> Add Bulk CT4 dist and sim

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/braun_blanquet.py
- skfp/distances/ct4.py
- skfp/distances/dice.py
- skfp/distances/rand.py
- skfp/distances/simpson.py
- skfp/distances/tanimoto.py
- tests/distances/dice.py
> Add Bulk Dice sim and dist

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/ct4.py
- skfp/distances/dice.py
- skfp/distances/harris_lahey.py
- skfp/distances/tanimoto.py
- tests/distances/harris_lahey.py
> Bulk Harris-Lahey dist and sim, small prange improvements

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/kulczynski.py
- tests/distances/kulczynski.py
> Bulk Kulczynski dist and sim

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/kulczynski.py
- skfp/distances/mcconnaughey.py
- tests/distances/mcconnaughey.py
> Bulk McConnaughey dist and sim

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/braun_blanquet.py
- skfp/distances/ct4.py
- skfp/distances/dice.py
- skfp/distances/harris_lahey.py
- skfp/distances/kulczynski.py
- skfp/distances/rogot_goldberg.py
- skfp/distances/simpson.py
- skfp/distances/tanimoto.py
- tests/distances/rogot_goldberg.py
> Bulk Rogot-Goldberg dist and sim

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/russell.py
- tests/distances/russell.py
> Bulk Russell sim and dist

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/braun_blanquet.py
- skfp/distances/ct4.py
- skfp/distances/dice.py
- skfp/distances/harris_lahey.py
- skfp/distances/kulczynski.py
- skfp/distances/mcconnaughey.py
- skfp/distances/rand.py
- skfp/distances/rogot_goldberg.py
- skfp/distances/russell.py
- skfp/distances/simpson.py
- skfp/distances/sokal_sneath.py
- skfp/distances/tanimoto.py
- tests/distances/sokal_sneath.py
Also includes a general optimization and speedup of computation of other bulk functions.
> Add bulk Sokal-Sneath 2 sim and dist

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/braun_blanquet.py
- skfp/distances/fraggle.py
- tests/distances/fraggle.py
Bulk Fraggle similarity, last part of https://github.com/scikit-fingerprints/scikit-fingerprints/issues/228.
> Add bulk Fraggle similarity

- skfp/distances/mcconnaughey.py
Fixes a typo in McConnaughey bulk similarity that resulted in nondeterministic and buggy behavior.
> Fix McConnaughey bug

- docs/api_reference.rst
- docs/modules/applicability_domain.rst
- skfp/applicability_domain/__init__.py
- skfp/applicability_domain/bounding_box.py
- skfp/bases/base_ad_checker.py
- skfp/bases/base_filter.py
- skfp/distances/mcconnaughey.py
- skfp/filters/beyond_ro5.py
- tests/applicability_domain/bounding_box.py
- tests/applicability_domain/utils.py
- tests/bases/base_filter.py
- tests/bases/base_fp_transformer.py
- tests/bases/base_preprocessor.py
- tests/conftest.py
- tests/docs_tests.py
Base class for applicability methods and first method, bounding box - part of https://github.com/scikit-fingerprints/scikit-fingerprints/issues/424.
> Applicability domain bounding box

- skfp/datasets/tdc/adme/adme.py
> Add remaining TDC datasets docs for ADME

- docs/modules/distances.rst
- skfp/distances/__init__.py
- skfp/distances/fraggle.py
- skfp/distances/mcs.py
- tests/distances/common.py
- tests/distances/mcs.py
Implements MCS similarity, https://github.com/scikit-fingerprints/scikit-fingerprints/issues/437.
> Add MCS similarity

- docs/modules/applicability_domain.rst
- skfp/applicability_domain/__init__.py
- skfp/applicability_domain/bounding_box.py
- skfp/applicability_domain/convex_hull.py
- tests/applicability_domain/bounding_box.py
- tests/applicability_domain/convex_hull.py
- tests/applicability_domain/utils.py
Convex hull, part of https://github.com/scikit-fingerprints/scikit-fingerprints/issues/424.
> Convex hull applicability domain method

- skfp/datasets/tdc/adme/adme.py
Correcting metrics in docs that differed from those suggested by TDC
> Correct the metrics in TDC docs

- docs/modules/applicability_domain.rst
- skfp/applicability_domain/__init__.py
- skfp/applicability_domain/bounding_box.py
- skfp/applicability_domain/convex_hull.py
- skfp/applicability_domain/leverage.py
- skfp/bases/base_ad_checker.py
- tests/applicability_domain/bounding_box.py
- tests/applicability_domain/convex_hull.py
- tests/applicability_domain/leverage.py
Part of https://github.com/scikit-fingerprints/scikit-fingerprints/issues/424, leverage method for AD checking.
> Add leverage AD check

- .github/workflows/tests.yml
- Makefile
- poetry.lock
- pyproject.toml
- skfp/datasets/utils.py
Adds datasets caching on CI to reduce failures during tests, part of https://github.com/scikit-fingerprints/scikit-fingerprints/issues/444.
> Add datasets caching for CI

- examples/08_similarity_and_distance_metrics.ipynb
> Adjusted the tutorial based on new suggestions

- .github/workflows/tests.yml
- examples/08_similarity_and_distance_metrics.ipynb
Fixed output in notebook 8, which had an import error previously.
> Fix notebook 8 output
